#!/bin/sh -e

[ -d /devices ] || mkdir /devices

cat > /devices/$1 <<EOF
#!/bin/sh
exec ssh -p$SSH_REVERSE_PORT fio@localhost \$*
EOF
chmod +x /devices/$1

echo "entering infinite sleep loop"
while true; do sleep 10000; done
